### ISSUE TITLE
好多直播间不能看

### ISSUE THREAD

**Issue by itgoyo** [nswbmw/douyu-mac-app#1]
数码科技分区的直播间不能看（APP还是在全部直播里面展示的），一开始我以为是主播下播了，但是连续输入好几个该分区的主播，都是灰色的看不了，然后我又输入其他分区的主播，人数几十的人数一万多的，输入房间号的，在列表里都是灰色的能看视频的是不是人数达到某一个临界才能看？
![](http://omvbl46i3.bkt.clouddn.com/18-10-26/5905097.jpg)

**Comment by nswbmw** [comment]
可能检查是否在线的那块判断条件有点问题，我研究下

**Comment by nswbmw** [comment]
v1.1.1 已经修复
